# -*- coding: utf-8 -*-
"""CountingFail.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kyFHr7x85tPEu2PsjaUjoqWz2kcsWkC4
"""

score = input().split()

countF = 0

for s in score:
  if int(s)<60:
    countF+=1
print(s)